### ISSUE TITLE
logging library - standarizing...

### ISSUE THREAD

**Issue by hanasaki** [brockn/hdfs-nfs-proxy#2]
I see both log4j and slf4j depends in the pom.xml : any preference for one over the other?
I can make updates and standardise on one (suggest log4j).  Thoughts?

**Comment by brockn** [comment]
Sure, that sounds good!

**Comment by hanasaki** [comment]
Done and checked into my fork.  Ready for you to pull.
catch me on IM if anything needs discussing.
