### ISSUE TITLE
Readahead cache to improve performance

### ISSUE THREAD

**Issue by nickb937** [brockn/hdfs-nfs-proxy#6]
On a 1000Mbit network, I timed a copy of a 1.5GB file to local disk at 45 minutes.  The main reason I can find for this is that NFS read/write requests are limited to 64Kbytes, which translates to much slower Hadoop requests of 64Kbytes.

It may be a large performance win if the nfs-proxy answered all read-requests from a local disk based cache. Have the cache populated by nfs-proxy upon receiving a read-request whereby it grabs 64MBytes or 128MBytes from HDFS in one operation, then answers NFS requests from the data stored on local disk.  I think this could work well enough even if initially restricted to  files opened read-only.

**Comment by brockn** [comment]
Would it be possible to use a java profiler to time that?  Or perhaps while it's being run do kill -3 <pid of nfs proxy> five or ten times and then send me the output file?

I can get much better throughput in my test environment.

**Comment by nickb937** [comment]
With profiling, I found a lot of time spent calling 'whoami' from getCurrentUser().  Changing the if statement condition increased throughput from 0.7-1.0MBytes/sec to 6.10MBytes/sec:

Before:
  public static String getCurrentUser() {
    String user = System.getenv("USER");
    if(user != null) {

After:

  public static String getCurrentUser() {
    String user = System.getenv("USER");
    if(user == null) {

**Comment by nickb937** [comment]
With that change, time taken to copy 4.3GB took 5m17secs.

**Comment by brockn** [comment]
OK, I just introduced that bug. I am fixing it now...Sorry!

**Comment by brockn** [comment]
OK the bug is fixed now.  I also think the read ahead operation could speed up reads. I will add that to the list, otherwise patches are welcome!

**Comment by brockn** [comment]
Moved here https://github.com/cloudera/hdfs-nfs-proxy/issues/1
