### ISSUE TITLE
SecurityHandler fails on Windows NFS mount

### ISSUE THREAD

**Issue by Downchuck** [brockn/hdfs-nfs-proxy#8]
12/08/16 06:40:31 INFO rpc.RPCServer: class com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4Handler got client pc-hype2windev:50692
12/08/16 06:40:31 INFO rpc.ClientWorker: Got SecurityHandler of type com.cloudera.hadoop.hdfs.nfs.security.SecurityHandler
Exception in thread "RPCServer-pc-hype2windev50692" java.lang.OutOfMemoryError: Java heap space

From
C:\Users\user>mount -o fileaccess=7 \192.168.25.51\ X:

On hadoop 100 jar.

**Comment by brockn** [comment]
I assume you are using the built-in windows NFS client? That only supportes NFSv3 and this NFSv4.

**Comment by Downchuck** [comment]
You're correct.
